/* Renders each WhatTheCap screen from mock-data.js (generated by the app's
   own domain code). Query params pick the screen:
   ?screen=overview|heatmap|apps|settings|onboarding|menubar
   &range=today|week|month  &layout=iso-es|ansi
   &state=empty|pausedByUser|secureInput|permissionDenied  &step=0|1|2 */

const params = new URLSearchParams(location.search);
const screen = params.get("screen") || "overview";
const rangeKey = params.get("range") || "today";
const layoutId = params.get("layout") || "iso-es";
const state = params.get("state") || "active";
const step = Number(params.get("step") || 0);

const D = window.WTC;
const R = D.ranges[rangeKey];

const fmt = (n) => n.toLocaleString("en-US");
const compact = (n) =>
	new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(n);
const pct = (n, digits = 1) => (n * 100).toFixed(digits) + "%";

function el(tag, cls, text) {
	const node = document.createElement(tag);
	if (cls) node.className = cls;
	if (text !== undefined) node.textContent = text;
	return node;
}

function html(tag, cls, inner) {
	const node = el(tag, cls);
	node.innerHTML = inner;
	return node;
}

// Mirrors Theme.heat: keycap -> ember-deep -> ember -> near-white.
function heatColor(t) {
	const stops = [
		[0.0, [0x1a, 0x17, 0x12]],
		[0.5, [0xb4, 0x65, 0x1b]],
		[0.85, [0xf2, 0xa3, 0x3c]],
		[1.0, [0xff, 0xe3, 0xb8]],
	];
	t = Math.min(Math.max(t, 0), 1);
	for (let i = 1; i < stops.length; i++) {
		if (t <= stops[i][0]) {
			const [t0, a] = stops[i - 1];
			const [t1, b] = stops[i];
			const k = (t - t0) / (t1 - t0);
			const mix = a.map((v, j) => Math.round(v + (b[j] - v) * k));
			return `rgb(${mix.join(",")})`;
		}
	}
	return "rgb(255,227,184)";
}

const icons = {
	overview: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M5 20v-8M12 20V5M19 20v-5"/></svg>',
	heatmap: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><rect x="2.5" y="7" width="19" height="11" rx="2"/><path d="M6.5 11h.01M10.5 11h.01M14.5 11h.01M17.5 11h.01M7.5 14.5h9"/></svg>',
	apps: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="4" y="4" width="7" height="7" rx="1.5"/><rect x="14" y="4" width="7" height="7" rx="1.5"/><rect x="4" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg>',
	settings: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M4 8h16M4 16h16"/><circle cx="9" cy="8" r="2.2" fill="var(--bg-inset)"/><circle cx="15" cy="16" r="2.2" fill="var(--bg-inset)"/></svg>',
	pause: '<svg viewBox="0 0 24 24" fill="currentColor"><rect x="7" y="5" width="3.4" height="14" rx="1.2"/><rect x="13.6" y="5" width="3.4" height="14" rx="1.2"/></svg>',
	shield: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"><path d="M12 3l7 3v5c0 4.5-3 8.5-7 10-4-1.5-7-5.5-7-10V6l7-3z"/><path d="M9.5 11.5l2 2 3.5-3.5"/></svg>',
	keyboard: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><rect x="2.5" y="7" width="19" height="11" rx="2"/><path d="M6.5 11h.01M10.5 11h.01M14.5 11h.01M17.5 11h.01M7.5 14.5h9"/></svg>',
	keyboardSlash: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><rect x="2.5" y="7" width="19" height="11" rx="2"/><path d="M7.5 14.5h9M4 4l17 17"/></svg>',
	hand: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M8 12V6a1.5 1.5 0 013 0v5V4.5a1.5 1.5 0 013 0V11v-4a1.5 1.5 0 013 0v6.8c0 3.4-2.4 6.2-6 6.2-3 0-4.5-1.4-6.5-4.8l-1.2-2.1a1.4 1.4 0 012.3-1.5L8 14"/></svg>',
	power: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 3v8M6.3 7a8 8 0 1011.4 0"/></svg>',
};

const stateMeta = {
	pausedByUser: { label: "Paused", detail: "You paused counting. Nothing is recorded until you resume.", tone: "ember", icon: icons.pause },
	secureInput: { label: "Secure input", detail: "A password field has secure input enabled. WTC pauses itself and records nothing.", tone: "calm", icon: icons.shield },
};

// ---- Window scaffold ----

function buildWindow(selectedScreen, captureState) {
	const win = el("div", "window");
	win.appendChild(html("div", "traffic", "<span></span><span></span><span></span>"));

	const rail = el("div", "rail");
	const mark = el("div", "wordmark");
	mark.appendChild(el("div", "big", "WTC"));
	mark.appendChild(el("div", "small", "WHAT THE CAP"));
	rail.appendChild(mark);

	const nav = el("div", "nav");
	for (const [id, title] of [["overview", "Overview"], ["heatmap", "Heatmap"], ["apps", "Per app"], ["settings", "Settings"]]) {
		const item = el("div", "nav-item" + (id === selectedScreen ? " selected" : ""));
		item.innerHTML = icons[id];
		item.appendChild(el("span", null, title));
		nav.appendChild(item);
	}
	rail.appendChild(nav);

	const footer = el("div", "rail-footer");
	footer.appendChild(el("div", "rule"));
	const badgeLabels = { active: "COUNTING", pausedByUser: "PAUSED", secureInput: "SECURE INPUT", permissionDenied: "NO PERMISSION" };
	const badgeState = captureState === "empty" ? "active" : captureState;
	const badge = el("div", "badge");
	badge.appendChild(el("span", "dot " + badgeState));
	badge.appendChild(el("span", null, badgeLabels[badgeState]));
	footer.appendChild(badge);
	footer.appendChild(html("div", "rail-note", "Counts per key code.<br>Never what you type."));
	rail.appendChild(footer);
	win.appendChild(rail);

	const content = el("div", "content");
	win.appendChild(content);
	return { win, content };
}

function pageHead(content, title, sub, withRange) {
	const head = el("div", "page-head");
	const left = el("div");
	left.appendChild(el("div", "page-title", title));
	left.appendChild(el("div", "page-sub", sub));
	head.appendChild(left);
	if (withRange) {
		const picker = el("div", "range-picker");
		for (const key of ["today", "week", "month"]) {
			picker.appendChild(el("span", "range-pill" + (key === rangeKey ? " selected" : ""), D.ranges[key].label));
		}
		head.appendChild(picker);
	}
	content.appendChild(head);
	return content;
}

function banner(tone, icon, title, detail, action) {
	const b = el("div", "banner " + tone);
	b.appendChild(html("span", "icon", icon));
	const text = el("div");
	text.appendChild(el("div", "title", title));
	text.appendChild(el("div", "detail", detail));
	b.appendChild(text);
	b.appendChild(el("div", "spacer"));
	if (action) b.appendChild(el("span", "btn prominent", action));
	return b;
}

function keycap(legend, sub, heatT, control, w, h) {
	const cap = el("div", "keycap" + (control ? " control" : ""));
	cap.style.width = w + "px";
	cap.style.height = h + "px";
	if (heatT > 0.02) {
		cap.style.background = heatColor(heatT);
		cap.style.borderColor = `rgba(242,163,60,${0.25 + 0.4 * heatT})`;
		if (heatT > 0.3) cap.style.boxShadow = `0 0 7px rgba(242,163,60,${0.35 * heatT})`;
	}
	if (sub) cap.appendChild(el("span", "sub", sub));
	const main = el("span", null, legend);
	if (heatT > 0.55) {
		main.style.color = "rgba(0,0,0,0.8)";
		if (sub) cap.firstChild.style.color = "rgba(0,0,0,0.55)";
	}
	cap.appendChild(main);
	return cap;
}

// ---- Screens ----

function renderOverview(content) {
	const page = el("div", "page");
	pageHead(page, "Overview", D.dateLabel, true);

	const hero = el("div");
	hero.appendChild(el("div", "hero-number", fmt(R.total)));
	const meta = el("div", "hero-meta");
	const rangeNoun = { today: "today", week: "7 days", month: "30 days" }[rangeKey];
	meta.appendChild(el("span", "what", `keystrokes · ${rangeNoun}`));
	if (R.previous > 0) {
		const delta = (R.total - R.previous) / R.previous;
		const cmp = rangeKey === "today" ? "day" : rangeNoun;
		meta.appendChild(el("span", "delta " + (delta >= 0 ? "up" : "down"),
			`${delta >= 0 ? "▲" : "▼"} ${pct(Math.abs(delta), 0)}  vs previous ${cmp}`));
	}
	hero.appendChild(meta);
	page.appendChild(hero);

	const chart = el("div", "card");
	chart.appendChild(el("div", "section-label", rangeKey === "today" ? "By hour" : "By day"));
	const dense = R.bars.length > 12;
	const bars = el("div", "bars" + (dense ? " dense" : ""));
	const peak = Math.max(...R.bars.map((b) => b.value), 1);
	const labelEvery = dense ? 5 : 1;
	R.bars.forEach((b, i) => {
		const col = el("div", "bar-col");
		const bar = el("div", "bar" + (b.isCurrent ? " current" : ""));
		bar.style.height = Math.max(3, (b.value / peak) * 120) + "px";
		col.appendChild(bar);
		col.appendChild(el("div", "bar-label" + (b.isCurrent ? " current" : ""), i % labelEvery === 0 ? b.label : " "));
		bars.appendChild(col);
	});
	chart.appendChild(bars);
	page.appendChild(chart);

	const top = el("div", "card");
	top.appendChild(el("div", "section-label", "Top keys"));
	const row = el("div", "top-keys");
	R.topKeys.forEach((k, i) => {
		const cell = el("div", "top-key");
		cell.appendChild(keycap(k.code === 49 ? "␣" : k.legend, null, 1 - i * 0.11, false, 46, 46));
		cell.appendChild(el("span", "count", compact(k.count)));
		cell.appendChild(el("span", "share", pct(k.count / R.total)));
		row.appendChild(cell);
	});
	top.appendChild(row);
	page.appendChild(top);
	content.appendChild(page);
}

function renderHeatmap(content) {
	const layout = D.layouts.find((l) => l.id === layoutId);
	const page = el("div", "page");
	pageHead(page, "Heatmap", `Per-key intensity · ${R.label.toLowerCase()}`, true);

	const toggle = el("div", "layout-toggle");
	for (const l of D.layouts) {
		toggle.appendChild(el("span", "layout-opt" + (l.id === layoutId ? " selected" : ""), l.name));
	}
	page.appendChild(toggle);

	const card = el("div", "card");
	const kb = el("div", "keyboard");
	card.appendChild(kb);
	page.appendChild(card);

	const peak = Math.max(...Object.values(R.keyCounts), 1);
	const footer = el("div", "heat-footer");
	const legend = el("div", "heat-legend");
	legend.appendChild(el("span", "cold", "COLD"));
	legend.appendChild(el("span", "scale"));
	legend.appendChild(el("span", "hot", "HOT"));
	footer.appendChild(legend);

	const readout = el("div", "readout");
	const sample = R.topKeys[1];
	readout.appendChild(el("span", "legend", sample.legend));
	readout.appendChild(el("span", "code", "key " + sample.code));
	readout.appendChild(el("span", "count", fmt(sample.count)));
	readout.appendChild(el("span", "share", pct(sample.count / R.total)));
	footer.appendChild(readout);
	page.appendChild(footer);
	content.appendChild(page);

	// Sized after insertion so widths derive from the real container.
	const width = kb.clientWidth - 8;
	const unit = (width - 6 * 14) / 15;
	for (const rowDef of layout.rows) {
		const rowEl = el("div", "kb-row");
		for (const key of rowDef) {
			const w = unit * key.width + 6 * (key.width - 1);
			if (key.code === null || key.code === undefined) {
				const spacer = el("div");
				spacer.style.width = w + "px";
				rowEl.appendChild(spacer);
				continue;
			}
			const count = R.keyCounts[String(key.code)] || 0;
			const t = Math.pow(count / peak, 0.6);
			rowEl.appendChild(keycap(key.legend, key.sub, t, key.control, w, unit));
		}
		kb.appendChild(rowEl);
	}
}

function renderApps(content) {
	const page = el("div", "page");
	pageHead(page, "Per app", `Where the keystrokes landed · ${R.label.toLowerCase()}`, true);

	const card = el("div", "card");
	const rows = el("div", "app-rows");
	const peak = R.apps[0].count;
	const total = R.apps.reduce((a, b) => a + b.count, 0);
	R.apps.forEach((app, i) => {
		const row = el("div", "app-row");
		row.appendChild(el("div", "app-rank" + (i < 3 ? " top" : ""), String(i + 1)));
		const main = el("div", "app-main");
		const line = el("div", "app-line");
		line.appendChild(el("span", "app-id", app.bundleID));
		line.appendChild(el("span", "app-count", fmt(app.count)));
		line.appendChild(el("span", "app-share", pct(app.count / total)));
		main.appendChild(line);
		const track = el("div", "app-bar-track");
		const bar = el("div", "app-bar" + (i < 3 ? " top" : ""));
		bar.style.width = Math.max(0.5, (app.count / peak) * 100) + "%";
		track.appendChild(bar);
		main.appendChild(track);
		row.appendChild(main);
		rows.appendChild(row);
	});
	card.appendChild(rows);
	page.appendChild(card);

	const note = el("div", "foot-note");
	note.innerHTML = `<span style="width:14px;color:var(--ink-faint)">${icons.hand}</span>`;
	note.appendChild(el("span", null, "WTC stores the bundle identifier and a count. Never window titles, documents, or text."));
	page.appendChild(note);
	content.appendChild(page);
}

function settingRow(rows, title, detail, accessory) {
	const row = el("div", "setting-row");
	const grow = el("div", "grow");
	grow.appendChild(el("div", "setting-title", title));
	grow.appendChild(el("div", "setting-detail", detail));
	row.appendChild(grow);
	row.appendChild(accessory);
	rows.appendChild(row);
	return row;
}

function renderSettings(content) {
	const page = el("div", "page");
	const head = el("div", "page-head");
	const left = el("div");
	left.appendChild(el("div", "page-title", "Settings"));
	left.appendChild(el("div", "page-sub", "Everything stays on this Mac"));
	head.appendChild(left);
	page.appendChild(head);

	const col = el("div", "settings-col");

	const general = el("div", "card");
	general.appendChild(el("div", "section-label", "General"));
	let rows = el("div", "setting-rows");
	settingRow(rows, "Launch at login", "Start counting when you sign in.", el("div", "switch on"));
	rows.appendChild(el("div", "rule"));
	settingRow(rows, "Pause counting", "Stop tallying until you resume.", el("div", "switch"));
	general.appendChild(rows);
	col.appendChild(general);

	const data = el("div", "card");
	data.appendChild(el("div", "section-label", "Data"));
	rows = el("div", "setting-rows");
	settingRow(rows, "Export counts as CSV", "Key code, legend, and count. The export contains no typed text because none is stored.", el("span", "btn", "Export…"));
	rows.appendChild(el("div", "rule"));
	settingRow(rows, "Reset all counts", "Deletes every tally on this Mac. There is no cloud copy to restore from.", el("span", "btn danger", "Reset…"));
	data.appendChild(rows);
	col.appendChild(data);

	const privacy = el("div", "card");
	privacy.appendChild(el("div", "section-label", "Privacy"));
	const pRows = el("div", "privacy-rows");
	const items = [
		"Counts are kept per key code. Key order is never stored, so nothing can be replayed.",
		"Secure input fields, like password boxes, pause counting automatically.",
		"Data lives in a local file. WTC has no network access to your counts.",
		"WTC is a visible app with a menu bar presence. No stealth mode exists.",
	];
	const pIcons = [icons.overview, icons.shield, icons.apps, icons.keyboard];
	items.forEach((text, i) => {
		const row = el("div", "privacy-row");
		row.innerHTML = `<span class="icon" style="width:14px">${pIcons[i]}</span>`;
		row.appendChild(el("span", null, text));
		pRows.appendChild(row);
	});
	privacy.appendChild(pRows);
	col.appendChild(privacy);

	const demo = el("div", "card");
	demo.appendChild(el("div", "section-label", "Design demo"));
	rows = el("div", "setting-rows");
	settingRow(rows, "Capture state", "Preview banners and blocked states.", el("span", "select", "Counting"));
	rows.appendChild(el("div", "rule"));
	settingRow(rows, "Mock data", "Restore the seeded dataset after a reset.", el("span", "btn", "Restore"));
	demo.appendChild(rows);
	col.appendChild(demo);

	page.appendChild(col);
	content.appendChild(page);
}

function renderStatePage(content, kind) {
	const page = el("div", "state-page");
	if (kind === "empty") {
		page.appendChild(html("div", "state-glyph dim", icons.keyboard));
		page.appendChild(el("div", "state-title", "Nothing counted yet"));
		page.appendChild(el("div", "state-detail", "Counts appear the moment you type anywhere. WTC tallies key codes only, so there is nothing to review or redact."));
		const actions = el("div", "state-actions");
		actions.appendChild(el("span", "btn prominent", "Restore mock data"));
		page.appendChild(actions);
	} else {
		page.appendChild(html("div", "state-glyph danger", icons.keyboardSlash));
		page.appendChild(el("div", "state-title", "Input Monitoring needed"));
		page.appendChild(el("div", "state-detail", "macOS blocks listen-only key-event taps until you grant Input Monitoring. WTC is idle and counting nothing right now."));
		const actions = el("div", "state-actions");
		actions.appendChild(el("span", "btn prominent", "Open System Settings"));
		actions.appendChild(el("span", "btn", "Run onboarding"));
		page.appendChild(actions);
	}
	content.appendChild(page);
}

function renderOnboarding(root) {
	const backdrop = el("div", "backdrop");
	const sheet = el("div", "sheet");

	if (step === 0) {
		const body = el("div", "sheet-body centered");
		const mark = el("div", "wordmark");
		mark.style.padding = "0";
		mark.style.textAlign = "center";
		mark.appendChild(el("div", "big", "WTC"));
		mark.appendChild(el("div", "small", "WHAT THE CAP"));
		body.appendChild(mark);
		body.appendChild(el("div", "ob-title", "Your keyboard, in numbers."));
		body.appendChild(html("div", "ob-text", "WTC counts how often each key gets pressed.<br>It never records what you type."));
		const caps = el("div", "top-keys");
		caps.style.marginTop = "8px";
		["H", "O", "L", "A"].forEach((ch, i) => caps.appendChild(keycap(ch, null, 0.25 + i * 0.22, false, 40, 40)));
		body.appendChild(caps);
		sheet.appendChild(body);
	} else if (step === 1) {
		const body = el("div", "sheet-body");
		body.appendChild(el("div", "section-label", "The privacy contract"));
		const title = el("div", "ob-title", "Counts, never content.");
		title.style.marginTop = "14px";
		body.appendChild(title);
		const rows = el("div", "contract-rows");
		const contract = [
			[icons.overview, "Per-key tallies only", "WTC stores \u201Ckey 14 was pressed 1,205 times today\u201D. Key order is never kept, so words and passwords cannot be reconstructed."],
			[icons.shield, "Secure input pauses everything", "When macOS flags a password field, WTC stops counting by itself and says so in the menu bar."],
			[icons.apps, "Local only", "Counts stay in a file on this Mac. Nothing about your typing crosses the network."],
			[icons.keyboard, "Always visible", "WTC lives in your menu bar and Dock. There is no hidden mode."],
		];
		for (const [icon, t, d] of contract) {
			const row = el("div", "contract-row");
			row.innerHTML = `<span class="icon">${icon}</span>`;
			const text = el("div");
			text.appendChild(el("div", "title", t));
			text.appendChild(el("div", "detail", d));
			row.appendChild(text);
			rows.appendChild(row);
		}
		body.appendChild(rows);
		sheet.appendChild(body);
	} else {
		const body = el("div", "sheet-body");
		body.appendChild(el("div", "section-label", "One permission"));
		const title = el("div", "ob-title", "Input Monitoring");
		title.style.margin = "14px 0";
		body.appendChild(title);
		body.appendChild(el("div", "ob-text", "macOS only lets an app observe key-down events through Input Monitoring. WTC uses it to increment one counter per key code, and for nothing else."));
		const card = el("div", "card");
		card.style.marginTop = "22px";
		const path = el("div", "perm-path");
		path.innerHTML = `<span style="width:16px;color:var(--ink-dim)">${icons.settings}</span>`;
		path.appendChild(el("span", null, "System Settings › Privacy & Security › Input Monitoring"));
		card.appendChild(path);
		card.appendChild(el("div", "perm-hint", "Toggle on What the cap, then come back here."));
		card.appendChild(el("span", "btn prominent", "Open System Settings"));
		body.appendChild(card);
		const status = el("div", "mock-status");
		status.appendChild(el("span", "dot"));
		status.appendChild(el("span", null, "Waiting for permission · mock status in the design build"));
		body.appendChild(status);
		sheet.appendChild(body);
	}

	const footer = el("div", "sheet-footer");
	const dots = el("div", "dots");
	for (let i = 0; i < 3; i++) dots.appendChild(el("span", i === step ? "on" : ""));
	footer.appendChild(dots);
	if (step > 0) footer.appendChild(el("span", "btn", "Back"));
	footer.appendChild(el("span", "btn prominent", step === 2 ? "Start counting" : "Continue"));
	sheet.appendChild(footer);
	backdrop.appendChild(sheet);
	root.appendChild(backdrop);
}

function renderMenubar(root) {
	const desktop = el("div", "desktop");
	const bar = el("div", "menubar");
	const wtc = el("span", "wtc-item");
	wtc.innerHTML = `<span style="width:15px;display:inline-flex">${icons.keyboard}</span>`;
	wtc.appendChild(el("span", null, compact(D.ranges.today.total)));
	bar.appendChild(wtc);
	bar.appendChild(el("span", "status", new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })));
	desktop.appendChild(bar);

	const dd = el("div", "dropdown");
	const head = el("div", "dropdown-head");
	const line = el("div", "rowline");
	const mark = el("span", "mark", "WTC");
	line.appendChild(mark);
	const badge = el("div", "badge");
	badge.style.paddingLeft = "0";
	badge.appendChild(el("span", "dot active"));
	badge.appendChild(el("span", null, "COUNTING"));
	line.appendChild(badge);
	head.appendChild(line);
	head.appendChild(el("div", "dropdown-number", fmt(D.ranges.today.total)));
	head.appendChild(el("div", "dropdown-sub", "keystrokes today"));
	dd.appendChild(head);

	const actions = el("div", "dropdown-actions");
	const items = [
		[icons.pause, "Pause counting", false],
		[icons.overview, "Open What the cap", true],
		[icons.power, "Quit", false],
	];
	for (const [icon, title, hover] of items) {
		const action = el("div", "menu-action" + (hover ? " hover" : ""));
		action.innerHTML = `<span class="icon" style="width:16px;display:inline-flex">${icon}</span>`;
		action.appendChild(el("span", null, title));
		actions.appendChild(action);
	}
	dd.appendChild(actions);
	desktop.appendChild(dd);
	root.appendChild(desktop);
}

// ---- Compose ----

const root = document.body;

if (screen === "menubar") {
	renderMenubar(root);
} else {
	const captureState = state === "empty" ? "active" : state;
	const { win, content } = buildWindow(screen === "onboarding" ? "overview" : screen, captureState);
	root.appendChild(win);

	if (state === "permissionDenied") {
		renderStatePage(content, "denied");
	} else if (state === "empty") {
		renderStatePage(content, "empty");
	} else {
		if (stateMeta[state]) {
			const m = stateMeta[state];
			content.appendChild(banner(m.tone, m.icon, m.label, m.detail, state === "pausedByUser" ? "Resume" : null));
		}
		if (screen === "heatmap") renderHeatmap(content);
		else if (screen === "apps") renderApps(content);
		else if (screen === "settings") renderSettings(content);
		else renderOverview(content);
	}

	if (screen === "onboarding") renderOnboarding(root);
}
